version: '3.8'

services:
  api:
      build:
        dockerfile: Dockerfile
        context: "./server"
      ports:
        - 5000:5000
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        PORT: 5000
        DB_URL: mongodb+srv://liza:liza@cluster0.vv9v1ok.mongodb.net/?retryWrites=true&w=majority
        JWT_ACCESS_SECRET: kdjcd3nGcd_s3js#Fgt3hth_rkStc_d@5vd_khjh
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
